"""add post_category & post

Revision ID: 8ea161af29bb
Revises: 2d9a8740551d
Create Date: 2022-05-07 07:38:23.166342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea161af29bb'
down_revision = '2d9a8740551d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_post_categories_id'), 'post_categories', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('validated', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['category'], ['post_categories.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_post_categories_id'), table_name='post_categories')
    op.drop_table('post_categories')
    # ### end Alembic commands ###
